### ISSUE TITLE
any way to change bot name from yui to something else

### ISSUE THREAD

**Issue by imvikashdev** [Itz-fork/Yui#2]

**Comment by partiallywritten** [comment]
Implemented in [commit: 52](https://github.com/Itz-fork/Yui/commit/2222ec55529fa05de9d24496de8696f893852ba1)

**Comment by partiallywritten** [comment]
Implemented in [commit: 52](https://github.com/Itz-fork/Yui/commit/2222ec55529fa05de9d24496de8696f893852ba1)
